version: '3.8'

services:
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    container_name: activemq
    ports:
      - "8161:8161"     # 웹 관리자 UI
      - "61616:61616"   # OpenWire 포트 (exploit.py 사용 대상)
    restart: unless-stopped
